name: Build

on:  
  workflow_dispatch:

env:  
  BUILD_PROFILE: debug
  RUST_TOOLCHAIN: nightly-2022-10-25

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
 
      - name: Save/Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
