name: Checks & Build

on:  
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Install minimal stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install minimal nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          
      - name: Initialize WASM build environment
        run: |
            rustup update stable
            rustup toolchain install nightly-2022-10-10
            rustup default nightly-2022-10-10
            rustup target add wasm32-unknown-unknown --toolchain nightly-2022-10-10    

      - name: Build
        run: cargo build --verbose
