name: Build

on:  
  workflow_dispatch:

env:  
  BUILD_PROFILE: debug
  RUST_TOOLCHAIN: nightly-2022-10-25

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
 
      - name: Save/Restore Dependencies from Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
     
      - name: Cache Binary
        uses: actions/cache@v3
        with:
          path: target/${{env.BUILD_PROFILE}}/ice
          key: ${{runner.os}}-${{env.RUST_TOOLCHAIN}}-${{github.sha}}
          
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
